/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package EjercicioCinco;

import javax.swing.JOptionPane;

/**
 *
 * @author liborio
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtLey = new javax.swing.JTextField();
        txtSSocial = new javax.swing.JTextField();
        txtSForzoso = new javax.swing.JTextField();
        txtCajaA = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSueldoT = new javax.swing.JTextField();
        txtSueldoB = new javax.swing.JTextField();
        cmdCalcular = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Descuentos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 31, 122, 34));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descuentos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Ley de politica pública");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Seguro social");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Seguro forzoso");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Caja de ahorro");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Sueldo Base");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        txtLey.setEditable(false);
        jPanel2.add(txtLey, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 100, -1));

        txtSSocial.setEditable(false);
        jPanel2.add(txtSSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 100, -1));

        txtSForzoso.setEditable(false);
        txtSForzoso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSForzosoActionPerformed(evt);
            }
        });
        jPanel2.add(txtSForzoso, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 100, -1));

        txtCajaA.setEditable(false);
        jPanel2.add(txtCajaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 100, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Sueldo Total");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        txtSueldoT.setEditable(false);
        jPanel2.add(txtSueldoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 100, -1));

        txtSueldoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSueldoBActionPerformed(evt);
            }
        });
        txtSueldoB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSueldoBKeyTyped(evt);
            }
        });
        jPanel2.add(txtSueldoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 100, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 320, 220));

        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSForzosoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSForzosoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSForzosoActionPerformed

    private void txtSueldoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSueldoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSueldoBActionPerformed

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed

        String Ley1, Seg2, For3, Caj4, SFinal;
        double Ley, Seg, For, Caj, Rest, ResF, Sbase;

        if (txtSueldoB.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por Favor Digite El Sueldo Base", "Error", JOptionPane.ERROR_MESSAGE);
            txtSueldoB.requestFocusInWindow();
            txtSueldoB.selectAll();
        } else {

            Sbase = Double.parseDouble(txtSueldoB.getText());
            Ley = (Sbase * 0.01);
            Seg = (Sbase * 0.04);
            For = (Sbase * 0.005);
            Caj = (Sbase * 0.05);
            Rest = (Ley + Seg + For + Caj);
            ResF = (Sbase - Rest);

            Ley1 = String.valueOf(Ley);
            txtLey.setText(Ley1);
            Seg2 = String.valueOf(Seg);
            txtSSocial.setText(Seg2);
            For3 = String.valueOf(For);
            txtSForzoso.setText(For3);
            Caj4 = String.valueOf(Caj);
            txtCajaA.setText(Caj4);
            SFinal = String.valueOf(ResF);
            txtSueldoT.setText(SFinal);


        }

    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void txtSueldoBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSueldoBKeyTyped

         char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtSueldoBKeyTyped

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        
     txtSueldoB.setText("");
     txtLey.setText("");
     txtSSocial.setText("");
     txtSForzoso.setText("");
     txtCajaA.setText("");
     txtSueldoT.setText("");
     txtSueldoB.requestFocusInWindow();
    }//GEN-LAST:event_cmdBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCajaA;
    private javax.swing.JTextField txtLey;
    private javax.swing.JTextField txtSForzoso;
    private javax.swing.JTextField txtSSocial;
    private javax.swing.JTextField txtSueldoB;
    private javax.swing.JTextField txtSueldoT;
    // End of variables declaration//GEN-END:variables
}
